In [1]:
import pandas as pd
dataframe= pd.read_csv('recipe.csv')
dataframe

,Unnamed: 0,Title,Ingredients,Instructions,Image_Name,Cleaned_Ingredients
0,0,Miso-Butter Roast Chicken With Acorn Squash Pa...,"['1 (3½–4-lb.) whole chicken', '2¾ tsp. kosher...","Pat chicken dry with paper towels, season all ...",miso-butter-roast-chicken-acorn-squash-panzanella,"['1 (3½–4-lb.) whole chicken', '2¾ tsp. kosher..."
1,1,Crispy Salt and Pepper Potatoes,"['2 large egg whites', '1 pound new potatoes (...",Preheat oven to 400°F and line a rimmed baking...,crispy-salt-and-pepper-potatoes-dan-kluger,"['2 large egg whites', '1 pound new potatoes (..."
2,2,Thanksgiving Mac and Cheese,"['1 cup evaporated milk', '1 cup whole milk', ...",Place a rack in middle of oven; preheat to 400...,thanksgiving-mac-and-cheese-erick-williams,"['1 cup evaporated milk', '1 cup whole milk', ..."
3,3,Italian Sausage and Bread Stuffing,"['1 (¾- to 1-pound) round Italian loaf, cut in...",Preheat oven to 350°F with rack in middle. Gen...,italian-sausage-and-bread-stuffing-240559,"['1 (¾- to 1-pound) round Italian loaf, cut in..."
4,4,Newton's Law,"['1 teaspoon dark brown sugar', '1 teaspoon ho...",Stir together brown sugar and hot water in a c...,newtons-law-apple-bourbon-cocktail,"['1 teaspoon dark brown sugar', '1 teaspoon ho..."
...,...,...,...,...,...,...
13496,13496,Brownie Pudding Cake,"['1 cup all-purpose flour', '2/3 cup unsweeten...",Preheat the oven to 350°F. Into a bowl sift to...,brownie-pudding-cake-14408,"['1 cup all-purpose flour', '2/3 cup unsweeten..."
13497,13497,Israeli Couscous with Roasted Butternut Squash...,"['1 preserved lemon', '1 1/2 pound butternut s...",Preheat oven to 475°F.\nHalve lemons and scoop...,israeli-couscous-with-roasted-butternut-squash...,"['1 preserved lemon', '1 1/2 pound butternut s..."
13498,13498,Rice with Soy-Glazed Bonito Flakes and Sesame ...,['Leftover katsuo bushi (dried bonito flakes) ...,"If using katsuo bushi flakes from package, moi...",rice-with-soy-glazed-bonito-flakes-and-sesame-...,['Leftover katsuo bushi (dried bonito flakes) ...
13499,13499,Spanakopita,['1 stick (1/2 cup) plus 1 tablespoon unsalted...,Melt 1 tablespoon butter in a 12-inch heavy sk...,spanakopita-107344,['1 stick (1/2 cup) plus 1 tablespoon unsalted...
13500,13500,"Mexican Poblano, Spinach, and Black Bean ""Lasa...",['12 medium to large fresh poblano chiles (2 1...,Lay 4 chiles on their sides on racks of gas bu...,mexican-poblano-spinach-and-black-bean-lasagne...,['12 medium to large fresh poblano chiles (2 1...

In [3]:
dataframe.isnull().sum()

Unnamed: 0             0
Title                  5
Ingredients            0
Instructions           8
Image_Name             0
Cleaned_Ingredients    0
dtype: int64

In [5]:
dataframe['Ingredients'][3]

"['1 (¾- to 1-pound) round Italian loaf, cut into 1-inch cubes (8 cups)', '2 tablespoons olive oil, divided', '2 pounds sweet Italian sausage, casings removed, divided', '1 stick unsalted butter, cut into pieces', '3 medium onions, chopped', '4 large celery ribs, chopped', '5 garlic cloves, minced', '4 large eggs, lightly beaten', '¾ cup heavy cream, divided', '½ cup turkey giblet stock or reduced-sodium chicken broth', '1 cup grated Parmigiano-Reggiano (2 ounces)', '½ cup coarsely chopped flat-leaf parsley', '4-qt shallow ceramic or glass baking dish']"

In [3]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
vectorizer=TfidfVectorizer()
X_ingredients=vectorizer.fit_transform(dataframe['Ingredients'])

In [5]:
dataframe

,Unnamed: 0,Title,Ingredients,Instructions,Image_Name,Cleaned_Ingredients
0,0,Miso-Butter Roast Chicken With Acorn Squash Pa...,"['1 (3½–4-lb.) whole chicken', '2¾ tsp. kosher...","Pat chicken dry with paper towels, season all ...",miso-butter-roast-chicken-acorn-squash-panzanella,"['1 (3½–4-lb.) whole chicken', '2¾ tsp. kosher..."
1,1,Crispy Salt and Pepper Potatoes,"['2 large egg whites', '1 pound new potatoes (...",Preheat oven to 400°F and line a rimmed baking...,crispy-salt-and-pepper-potatoes-dan-kluger,"['2 large egg whites', '1 pound new potatoes (..."
2,2,Thanksgiving Mac and Cheese,"['1 cup evaporated milk', '1 cup whole milk', ...",Place a rack in middle of oven; preheat to 400...,thanksgiving-mac-and-cheese-erick-williams,"['1 cup evaporated milk', '1 cup whole milk', ..."
3,3,Italian Sausage and Bread Stuffing,"['1 (¾- to 1-pound) round Italian loaf, cut in...",Preheat oven to 350°F with rack in middle. Gen...,italian-sausage-and-bread-stuffing-240559,"['1 (¾- to 1-pound) round Italian loaf, cut in..."
4,4,Newton's Law,"['1 teaspoon dark brown sugar', '1 teaspoon ho...",Stir together brown sugar and hot water in a c...,newtons-law-apple-bourbon-cocktail,"['1 teaspoon dark brown sugar', '1 teaspoon ho..."
...,...,...,...,...,...,...
13496,13496,Brownie Pudding Cake,"['1 cup all-purpose flour', '2/3 cup unsweeten...",Preheat the oven to 350°F. Into a bowl sift to...,brownie-pudding-cake-14408,"['1 cup all-purpose flour', '2/3 cup unsweeten..."
13497,13497,Israeli Couscous with Roasted Butternut Squash...,"['1 preserved lemon', '1 1/2 pound butternut s...",Preheat oven to 475°F.\nHalve lemons and scoop...,israeli-couscous-with-roasted-butternut-squash...,"['1 preserved lemon', '1 1/2 pound butternut s..."
13498,13498,Rice with Soy-Glazed Bonito Flakes and Sesame ...,['Leftover katsuo bushi (dried bonito flakes) ...,"If using katsuo bushi flakes from package, moi...",rice-with-soy-glazed-bonito-flakes-and-sesame-...,['Leftover katsuo bushi (dried bonito flakes) ...
13499,13499,Spanakopita,['1 stick (1/2 cup) plus 1 tablespoon unsalted...,Melt 1 tablespoon butter in a 12-inch heavy sk...,spanakopita-107344,['1 stick (1/2 cup) plus 1 tablespoon unsalted...
13500,13500,"Mexican Poblano, Spinach, and Black Bean ""Lasa...",['12 medium to large fresh poblano chiles (2 1...,Lay 4 chiles on their sides on racks of gas bu...,mexican-poblano-spinach-and-black-bean-lasagne...,['12 medium to large fresh poblano chiles (2 1...

In [6]:
X_ingredients

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 563134 stored elements and shape (13501, 7302)>

In [7]:
knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=5)
knn.fit(X_ingredients)

NearestNeighbors(algorithm='brute', metric='cosine')

In [9]:
distances, indices = knn.kneighbors(X_ingredients[0], n_neighbors=5)

In [10]:
for i in range(len(indices[0])):
    print(f"Recipe {i+1}: {dataframe.iloc[indices[0][i]]['Title']}")
    print(f"Distance: {distances[0][i]:.4f}\n")

Recipe 1: Miso-Butter Roast Chicken With Acorn Squash Panzanella
Distance: 0.0000

Recipe 2: Chicken Under a Skillet with Lemon Pan Sauce
Distance: 0.4420

Recipe 3: Bacon-Cheddar Muffins
Distance: 0.4636

Recipe 4: Classic Herb and Fennel Stuffing
Distance: 0.4688

Recipe 5: Shrimp Empanadas
Distance: 0.4706

In [11]:
def get_similar_recipes(index, n=5):
    distances, indices = knn.kneighbors(X_ingredients[index], n_neighbors=n)
    print(f"Input recipe: {dataframe.iloc[index]['Title']}\n")
    for i in range(1, n):
        recipe_title = dataframe.iloc[indices[0][i]]['Title']
        print(f"{i}. {recipe_title} (Distance: {distances[0][i]:.4f})")

In [12]:
get_similar_recipes(10)

Input recipe: Hot Pimento Cheese Dip

1. Arugula Pesto (Distance: 0.5892)
2. Drunken Chicken (Distance: 0.6138)
3. White Russian (Distance: 0.6231)
4. White Russian (Distance: 0.6231)

In [13]:
user_input = input("Enter ingredients you have: ")

user_vec = vectorizer.transform([user_input])
distances, indices = knn.kneighbors(user_vec, n_neighbors=5)

print("\nTop recipe matches:\n")
for i in range(len(indices[0])):
    title = dataframe.iloc[indices[0][i]]['Title']
    ingredients = dataframe.iloc[indices[0][i]]['Ingredients']
    print(f"{i+1}. {title}")
    print(f"   Ingredients: {ingredients[:150]}...\n")

Enter ingredients you have:  chicken, lemon, pork, onions

Top recipe matches:

1. Double-Pork Carnitas
   Ingredients: ['3 pounds boneless pork shoulder (Boston butt), cut into 1 1/2-inch pieces', '1 pound pork belly, cut into 1-inch pieces', '1 cup homemade chicken st...

2. Lan Pham's Herbed-Roasted Onions
   Ingredients: ['2 medium red onions', '2 medium yellow onions', '2 tablespoons fresh lemon juice', '1 teaspoon Dijon mustard', '2 garlic cloves, minced', '1 tablesp...

3. Fully Salted Roast Chicken
   Ingredients: ['1 (3 1/2–4-lb.) chicken', 'Kosher salt']...

4. Pork Chops with Mustard Sauce
   Ingredients: ['4 (3/4-inch-thick) pork chops', '3/4 teaspoon salt', '1/2 teaspoon black pepper', '2 tablespoons vegetable oil', '1/4 cup finely chopped shallots (1...

5. Caramelized Onions
   Ingredients: ['2 large yellow onions, peeled (about 1 pound)', '2 tablespoons unsalted butter', 'Kosher salt', 'Low-sodium chicken broth or water (for pan; optiona...

In [14]:
dataframe['Ingredients'] = dataframe['Ingredients'].apply(lambda x: " ".join(eval(x)) if isinstance(x, str) and x.startswith('[') else x)

In [15]:
user_input = input("Enter ingredients you have: ")

user_vec = vectorizer.transform([user_input])
distances, indices = knn.kneighbors(user_vec, n_neighbors=5)

print("\nTop recipe matches:\n")
for i in range(len(indices[0])):
    title = dataframe.iloc[indices[0][i]]['Title']
    ingredients = dataframe.iloc[indices[0][i]]['Ingredients']
    print(f"{i+1}. {title}")
    print(f"   Ingredients: {ingredients[:150]}...\n")

Enter ingredients you have:  chicken, tofu, onions, potatoes, rice

Top recipe matches:

1. Skillet Chicken and Vegetables
   Ingredients: 4 chicken thighs with skin and bone 1 tablespoon paprika 2 tablespoons vegetable oil 3/4 pound small red-skinned potatoes, halved 8 boiling onions, pe...

2. Marinated Tofu
   Ingredients: 1 pound extra-firm tofu 2 tablespoons low-sodium soy sauce 1 tablespoon orange juice 2 teaspoons sesame oil 1 teaspoon canola oil Cooking spray...

3. Creamy Ginger Dressing
   Ingredients: 1/3 cup silken tofu 1 teaspoon finely grated lemon zest 2 tablespoons fresh lemon juice 2 tablespoons unseasoned rice vinegar 1 teaspoon Dijon mustard...

4. Vegan Niçoise-Style Salad
   Ingredients: 1/2 cup extra- virgin olive oil 1/4 to 1/3 cup white or red wine vinegar, or to taste 1 tablespoon Dijon-style mustard 1 tablespoon natural granulated...

5. Creamy Potato Salad with Lemon and Fresh Herbs
   Ingredients: 3 pounds baby red potatoes 3 tablespoons unseasoned rice vinegar 3/4 cup mayonnaise 3 medium green onions, thinly sliced 1 celery stalk, cut into 1/3-...

In [1]:
import tkinter as tk
from tkinter import ttk, scrolledtext
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
import pandas as pd

# =========================
#  Load your dataset
# =========================
# Make sure 'dataframe' is already loaded, or load it here:
# dataframe = pd.read_csv("your_dataset.csv")

# Vectorize ingredients
vectorizer = TfidfVectorizer()
X_ingredients = vectorizer.fit_transform(dataframe['Ingredients'])

# Train KNN model
knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=5)
knn.fit(X_ingredients)

# =========================
#  Tkinter UI setup
# =========================
root = tk.Tk()
root.title("Recipe Recommender")
root.geometry("700x500")
root.configure(bg="#f5f5f5")

title_label = tk.Label(
    root, 
    text="🍳 Recipe Recommender", 
    font=("Helvetica", 20, "bold"), 
    bg="#f5f5f5", 
    fg="#333"
)
title_label.pack(pady=15)

# Input box
input_label = tk.Label(root, text="Enter ingredients you have:", font=("Helvetica", 12), bg="#f5f5f5")
input_label.pack()

input_box = tk.Entry(root, width=70, font=("Helvetica", 12))
input_box.pack(pady=10)

# Result box
result_box = scrolledtext.ScrolledText(root, width=80, height=15, font=("Helvetica", 11), wrap=tk.WORD)
result_box.pack(pady=10)

# =========================
#  Recommendation function
# =========================
def recommend_recipes():
    user_input = input_box.get()
    if not user_input.strip():
        result_box.delete(1.0, tk.END)
        result_box.insert(tk.END, "Please enter at least one ingredient.")
        return

    # Transform input and get nearest recipes
    user_vec = vectorizer.transform([user_input])
    distances, indices = knn.kneighbors(user_vec, n_neighbors=5)

    result_box.delete(1.0, tk.END)
    result_box.insert(tk.END, f"Top recipe matches for: '{user_input}'\n\n")

    for i in range(len(indices[0])):
        title = dataframe.iloc[indices[0][i]]['Title']
        ingredients = dataframe.iloc[indices[0][i]]['Ingredients']
        result_box.insert(tk.END, f"{i+1}. {title}\n")
        result_box.insert(tk.END, f"   Ingredients: {ingredients[:150]}...\n\n")

# Button
search_button = ttk.Button(root, text="Find Recipes", command=recommend_recipes)
search_button.pack(pady=10)

root.mainloop()

NameError: name 'dataframe' is not defined

In [1]:
import tkinter as tk
from tkinter import ttk, scrolledtext
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
import pandas as pd

# =========================
#  Load your dataset
# =========================
# Make sure 'dataframe' is already loaded, or load it here:
# dataframe = pd.read_csv("your_dataset.csv")

# Vectorize ingredients
vectorizer = TfidfVectorizer()
X_ingredients = vectorizer.fit_transform(dataframe['Ingredients'])

# Train KNN model
knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=5)
knn.fit(X_ingredients)

# =========================
#  Tkinter UI setup
# =========================
root = tk.Tk()
root.title("Recipe Recommender")
root.geometry("700x500")
root.configure(bg="#f5f5f5")

title_label = tk.Label(
    root, 
    text="🍳 Recipe Recommender", 
    font=("Helvetica", 20, "bold"), 
    bg="#f5f5f5", 
    fg="#333"
)
title_label.pack(pady=15)

# Input box
input_label = tk.Label(root, text="Enter ingredients you have:", font=("Helvetica", 12), bg="#f5f5f5")
input_label.pack()

input_box = tk.Entry(root, width=70, font=("Helvetica", 12))
input_box.pack(pady=10)

# Result box
result_box = scrolledtext.ScrolledText(root, width=80, height=15, font=("Helvetica", 11), wrap=tk.WORD)
result_box.pack(pady=10)

# =========================
#  Recommendation function
# =========================
def recommend_recipes():
    user_input = input_box.get()
    if not user_input.strip():
        result_box.delete(1.0, tk.END)
        result_box.insert(tk.END, "Please enter at least one ingredient.")
        return

    # Transform input and get nearest recipes
    user_vec = vectorizer.transform([user_input])
    distances, indices = knn.kneighbors(user_vec, n_neighbors=5)

    result_box.delete(1.0, tk.END)
    result_box.insert(tk.END, f"Top recipe matches for: '{user_input}'\n\n")

    for i in range(len(indices[0])):
        title = dataframe.iloc[indices[0][i]]['Title']
        ingredients = dataframe.iloc[indices[0][i]]['Ingredients']
        result_box.insert(tk.END, f"{i+1}. {title}\n")
        result_box.insert(tk.END, f"   Ingredients: {ingredients[:150]}...\n\n")

# Button
search_button = ttk.Button(root, text="Find Recipes", command=recommend_recipes)
search_button.pack(pady=10)

root.mainloop()

NameError: name 'dataframe' is not defined

In [2]:
dataframe = pd.read_csv("recipe.csv")

In [3]:
dataframe

,Unnamed: 0,Title,Ingredients,Instructions,Image_Name,Cleaned_Ingredients
0,0,Miso-Butter Roast Chicken With Acorn Squash Pa...,"['1 (3½–4-lb.) whole chicken', '2¾ tsp. kosher...","Pat chicken dry with paper towels, season all ...",miso-butter-roast-chicken-acorn-squash-panzanella,"['1 (3½–4-lb.) whole chicken', '2¾ tsp. kosher..."
1,1,Crispy Salt and Pepper Potatoes,"['2 large egg whites', '1 pound new potatoes (...",Preheat oven to 400°F and line a rimmed baking...,crispy-salt-and-pepper-potatoes-dan-kluger,"['2 large egg whites', '1 pound new potatoes (..."
2,2,Thanksgiving Mac and Cheese,"['1 cup evaporated milk', '1 cup whole milk', ...",Place a rack in middle of oven; preheat to 400...,thanksgiving-mac-and-cheese-erick-williams,"['1 cup evaporated milk', '1 cup whole milk', ..."
3,3,Italian Sausage and Bread Stuffing,"['1 (¾- to 1-pound) round Italian loaf, cut in...",Preheat oven to 350°F with rack in middle. Gen...,italian-sausage-and-bread-stuffing-240559,"['1 (¾- to 1-pound) round Italian loaf, cut in..."
4,4,Newton's Law,"['1 teaspoon dark brown sugar', '1 teaspoon ho...",Stir together brown sugar and hot water in a c...,newtons-law-apple-bourbon-cocktail,"['1 teaspoon dark brown sugar', '1 teaspoon ho..."
...,...,...,...,...,...,...
13496,13496,Brownie Pudding Cake,"['1 cup all-purpose flour', '2/3 cup unsweeten...",Preheat the oven to 350°F. Into a bowl sift to...,brownie-pudding-cake-14408,"['1 cup all-purpose flour', '2/3 cup unsweeten..."
13497,13497,Israeli Couscous with Roasted Butternut Squash...,"['1 preserved lemon', '1 1/2 pound butternut s...",Preheat oven to 475°F.\nHalve lemons and scoop...,israeli-couscous-with-roasted-butternut-squash...,"['1 preserved lemon', '1 1/2 pound butternut s..."
13498,13498,Rice with Soy-Glazed Bonito Flakes and Sesame ...,['Leftover katsuo bushi (dried bonito flakes) ...,"If using katsuo bushi flakes from package, moi...",rice-with-soy-glazed-bonito-flakes-and-sesame-...,['Leftover katsuo bushi (dried bonito flakes) ...
13499,13499,Spanakopita,['1 stick (1/2 cup) plus 1 tablespoon unsalted...,Melt 1 tablespoon butter in a 12-inch heavy sk...,spanakopita-107344,['1 stick (1/2 cup) plus 1 tablespoon unsalted...
13500,13500,"Mexican Poblano, Spinach, and Black Bean ""Lasa...",['12 medium to large fresh poblano chiles (2 1...,Lay 4 chiles on their sides on racks of gas bu...,mexican-poblano-spinach-and-black-bean-lasagne...,['12 medium to large fresh poblano chiles (2 1...

In [2]:
import pandas as pd
dataframe= pd.read_csv('recipe.csv')

In [4]:
import tkinter as tk
from tkinter import ttk, scrolledtext
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
import pandas as pd

# =========================
#  Load your dataset
# =========================
# Make sure 'dataframe' is already loaded, or load it here:
# dataframe = pd.read_csv("your_dataset.csv")

# Vectorize ingredients
vectorizer = TfidfVectorizer()
X_ingredients = vectorizer.fit_transform(dataframe['Ingredients'])

# Train KNN model
knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=5)
knn.fit(X_ingredients)

# =========================
#  Tkinter UI setup
# =========================
root = tk.Tk()
root.title("Recipe Recommender")
root.geometry("700x500")
root.configure(bg="#f5f5f5")

title_label = tk.Label(
    root, 
    text="🍳 Recipe Recommender", 
    font=("Helvetica", 20, "bold"), 
    bg="#f5f5f5", 
    fg="#333"
)
title_label.pack(pady=15)

# Input box
input_label = tk.Label(root, text="Enter ingredients you have:", font=("Helvetica", 12), bg="#f5f5f5")
input_label.pack()

input_box = tk.Entry(root, width=70, font=("Helvetica", 12))
input_box.pack(pady=10)

# Result box
result_box = scrolledtext.ScrolledText(root, width=80, height=15, font=("Helvetica", 11), wrap=tk.WORD)
result_box.pack(pady=10)

# =========================
#  Recommendation function
# =========================
def recommend_recipes():
    user_input = input_box.get()
    if not user_input.strip():
        result_box.delete(1.0, tk.END)
        result_box.insert(tk.END, "Please enter at least one ingredient.")
        return

    # Transform input and get nearest recipes
    user_vec = vectorizer.transform([user_input])
    distances, indices = knn.kneighbors(user_vec, n_neighbors=5)

    result_box.delete(1.0, tk.END)
    result_box.insert(tk.END, f"Top recipe matches for: '{user_input}'\n\n")

    for i in range(len(indices[0])):
        title = dataframe.iloc[indices[0][i]]['Title']
        ingredients = dataframe.iloc[indices[0][i]]['Ingredients']
        result_box.insert(tk.END, f"{i+1}. {title}\n")
        result_box.insert(tk.END, f"   Ingredients: {ingredients[:150]}...\n\n")

# Button
search_button = ttk.Button(root, text="Find Recipes", command=recommend_recipes)
search_button.pack(pady=10)

root.mainloop()